02.extensions/zoomailing/02.troubleshooting/02.faq/docs.md
https://zoolanders.zendesk.com/agent/tickets/6941
=> add zoomailing faq

02.extensions/zooseo/01.basics/06.faq/docs.md
https://github.com/JOOlanders/documentation/issues/39
=> feat(zooseo): add faq question about work with other sef ext

02.extensions/zoocart/01.basics/06.faq/docs.md
https://github.com/JOOlanders/documentation/issues/19
=> feat(zoocart): add about translation

02.extensions/zoocart/01.basics/06.faq/docs.md
https://github.com/JOOlanders/documentation/issues/20
=> update(zoocart): add faq about add new payment plugin

02.extensions/zoofilter/01.basics/05.faq/docs.md
https://github.com/JOOlanders/documentation/issues/23
=> update(zoofilter): how to search by related cats pro

02.extensions/zoofilter/01.basics/03.integration/docs.md
https://github.com/JOOlanders/documentation/issues/27
=> update(zoofilter): add note about not compatible elements

02.extensions/zoomailing/02.troubleshooting/03.faq/docs.md
https://github.com/JOOlanders/documentation/issues/16
=> update(zoomailing): add about dynamic content

02.extensions/zoomailing/02.troubleshooting/03.faq/docs.md
https://github.com/JOOlanders/documentation/issues/37
=> update(zoomailing): about edit styling

02.extensions/zoocart/01.basics/04.settings/_shipping/default.md, 02.extensions/zoocart/01.basics/06.faq/docs.md
https://github.com/JOOlanders/documentation/issues/22
=> update(zoocart): shipping rates conditions

02.extensions/zoocart/03.advanced/02.customizations/docs.md
https://github.com/JOOlanders/documentation/issues/57
=> update(zoocart): email customization

01.elements/texts/01.basics/06.faq/docs.md, 01.elements/texts/03.troubleshooting/02.known-issues/docs.md
Related PR https://github.com/JOOlanders/TextareaPro/pull/7
=> doc(texts): faq, known issue about editors

02.extensions/zoolanders/03.widgetkit/01.basics/docs.md
https://zoolanders.zendesk.com/agent/tickets/7441
=> fix(wk doc): fix info about layouts overriding

01.elements/mediapro/01.basics/04.layouts/docs.md, 01.elements/mediapro/02.advanced/04.cloud-front/docs.md
https://github.com/JOOlanders/documentation/issues/40
=> feat(mediapro): cloud front integration

01.elements/downloadpro/02.advanced/03.amazon-s3/docs.md, 01.elements/mediapro/02.advanced/03.amazon-s3/docs.md, 02.extensions/zoolanders/02.elements/03.fields/docs.md, _partials/elements/amazon-s3/default.md
https://github.com/JOOlanders/documentation/issues/74
=> feat(mediapro / downloadpro): add amazon info

02.extensions/zoofilter/01.basics/03.integration/docs.md, 02.extensions/zoofilter/01.basics/05.faq/docs.md
Once the https://github.com/JOOlanders/ZOOfilter/pull/61 will be approved and merged, the doc should be updated about new parameters / layouts
=> update(zoofilter): add info about Uikit layouts

02.extensions/zoocart/01.basics/06.faq/docs.md
https://zoolanders.zendesk.com/agent/tickets/7899
=> feat(zoocart): add info about wk2 to faq

02.extensions/zoocart/02.settings/04.discounts/docs.md
https://zoolanders.zendesk.com/agent/tickets/7910
=> add a note about guest checkout limitation

01.elements/googlemapspro/01.basics/05.faq/docs.md
https://zoolanders.zendesk.com/agent/tickets/8315
https://zoolanders.zendesk.com/agent/tickets/8323
https://zoolanders.zendesk.com/agent/tickets/8341
=> doc(google maps pro): added info about  request_denied error

02.extensions/zooitempro/01.basics/06.faq/docs.md, 02.extensions/zooport/01.basics/03.updating/docs.md, 04.faq/docs.md
1) zoo item pro support a single not repeatable dates
2) zooport update data (categories are not supported)
=> Doc update

01.elements/imagepro/01.basics/04.layouts/docs.md
Related to this commit https://github.com/joolanders/ImagePro/pull/66
=> feat(imagepro): add info about wk2 item link param

02.extensions/zoocart/01.basics/03.integration/docs.md
https://zoolanders.zendesk.com/agent/tickets/8840
=> feat(zoocart): added info about variation position; duration element value

02.extensions/zoolingual/01.basics/05.faq/docs.md
https://zoolanders.zendesk.com/agent/tickets/8889
=> doc(zoolingual): add note about application ordering by name

02.extensions/zoocart/03.plugins/01.payment-plugins/docs.md
https://zoolanders.zendesk.com/agent/tickets/8996
=> doc(paypal): note about https

02.extensions/zoocart/04.advanced/01.variations/docs.md
https://zoolanders.zendesk.com/agent/tickets/8851
=> doc(zoocart): variations on order/cart layout is deprecated

01.elements/downloadpro/01.basics/06.faq/docs.md, 04.faq/docs.md
https://zoolanders.zendesk.com/agent/tickets/8535
=> doc(download pro): added info about s3 regions support
